CREATE TABLE IF NOT EXISTS cities(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    id_state INT UNSIGNED NOT NULL,
    area DECIMAL(10,2),
    PRIMARY KEY (id),
    FOREIGN KEY (id_state) REFERENCES states (id)
);

CREATE TABLE IF NOT EXISTS test(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);

DROP TABLE IF  EXISTS test
